### ISSUE TITLE
Crash on changing to an old playlist tab

### ISSUE THREAD

**Issue by ripdog** [fooyin/fooyin#163]
Fooyin crashed, first triggered by switching to an old playlist after updating it. On restart, fooyin renders UI except contents of playlist then crashes again.

Stack trace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff5ea8eb3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff5e50a30 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5e384c3 in __GI_abort () at abort.c:79
#4  0x00007ffff5e39354 in __libc_message_impl (fmt=fmt@entry=0x7ffff5fc22ea "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007ffff5eb3085 in malloc_printerr (str=str@entry=0x7ffff5fc5988 "malloc(): unaligned tcache chunk detected") at malloc.c:5772
#6  0x00007ffff5eb794c in tcache_get_n (tc_idx=<optimized out>, ep=<optimized out>) at malloc.c:3183
#7  tcache_get (tc_idx=<optimized out>) at malloc.c:3199
#8  __GI___libc_malloc (bytes=284) at malloc.c:3320
#9  0x00007ffff6651ab8 in allocateData (allocSize=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydata.cpp:139
#10 allocateHelper (objectSize=2, alignment=16, capacity=<optimized out>, option=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydata.cpp:181
#11 allocateHelper (objectSize=2, alignment=16, capacity=<optimized out>, option=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydata.cpp:157
#12 QArrayData::allocate2 (dptr=0x7fff895fee20, capacity=<optimized out>, option=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydata.cpp:220
#13 0x00007ffff67f85b4 in QTypedArrayData<char16_t>::allocate (capacity=<optimized out>, option=QArrayData::KeepSize) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydata.h:138
#14 QArrayDataPointer<char16_t>::QArrayDataPointer (this=<optimized out>, alloc=<optimized out>, n=<optimized out>, option=QArrayData::KeepSize) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydatapointer.h:58
#15 QString::QString(long long, Qt::Initialization) [clone .constprop.1] (this=0x7fff895fee60, size=133) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstring.cpp:2542
#16 0x00007ffff663562e in QUtf8::convertToUnicode (in=..., state=0x7fff895fef58) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstringconverter.cpp:672
#17 QLocal8Bit::convertToUnicode (in=..., state=0x7fff895fef58) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstringconverter_p.h:358
#18 fromLocal8Bit (out=0x7ffef40027a0, in=..., state=0x7fff895fef58) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstringconverter.cpp:1724
#19 0x00007ffff6584ff4 in QStringDecoder::decodeAsString (this=0x7fff895fef50, in=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/tools/qarraydatapointer.h:119
#20 0x00007ffff6617ad9 in QStringDecoder::EncodedData<QByteArrayView>::operator QString (this=0x7fff895fef30) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstringconverter.h:104
#21 QString::fromLocal8Bit (ba=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstring.cpp:5836
#22 0x00007ffff64db5dd in QString::fromLocal8Bit<void> (ba=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/text/qstring.h:658
#23 0x00007ffff65101d0 in QFile::decodeName (localFileName=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfile.h:164
#24 QFileSystemEntry::resolveFilePath (this=this@entry=0x7fff895ff1f0) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfilesystementry.cpp:112
#25 0x00007ffff6510249 in QFileSystemEntry::filePath (this=this@entry=0x7fff895ff1f0) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfilesystementry.cpp:96
#26 0x00007ffff6515486 in _q_resolveEntryAndCreateLegacyEngine_recursive (entry=..., data=..., engine=@0x7fff895ff1c8: 0x0, resolvingEntry=resolvingEntry@entry=false) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfilesystemengine.cpp:102
#27 0x00007ffff6515be2 in QFileSystemEngine::resolveEntryAndCreateLegacyEngine (entry=..., data=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfilesystemengine.cpp:161
#28 0x00007ffff6501bfe in QFileInfoPrivate::QFileInfoPrivate (this=0x7ffef4003480, file=..., data=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qfileinfo_p.h:84
#29 QDirIteratorPrivate::advance (this=this@entry=0x7ffef4009340) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qdiriterator.cpp:234
#30 0x00007ffff650276b in QDirIteratorPrivate::QDirIteratorPrivate (this=<optimized out>, entry=..., nameFilters=..., _filters=..., flags=..., resolveEngine=<optimized out>, this=<optimized out>, entry=..., nameFilters=..., _filters=..., flags=..., 
    resolveEngine=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qdiriterator.cpp:151
#31 0x00007ffff650301d in QDirIterator::QDirIterator (this=<optimized out>, path=..., nameFilters=..., filters=..., flags=..., this=<optimized out>, path=..., nameFilters=..., filters=..., flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qdiriterator.cpp:443
#32 0x00007ffff64fa756 in QDir::entryList (this=this@entry=0x7fff895ff5f8, nameFilters=..., filters=..., filters@entry=..., sort=..., sort@entry=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/io/qdir.cpp:1430
#33 0x00007ffff7c92cb9 in Fooyin::CoverProvider::Private::findDirectoryCover (this=0x5555558f3120, track=..., type=<optimized out>) at /usr/include/qt6/QtCore/qarraydataops.h:340
#34 Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}::operator()() const (__closure=__closure@entry=0x7fff895ff760) at /usr/src/debug/fooyin-git/fooyin-git/src/gui/coverprovider.cpp:199
#35 0x00007ffff7c93f21 in std::__invoke_impl<Fooyin::CoverProvider::Private::CoverLoaderResult, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&>(std::__invoke_other, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&) (__f=...) at /usr/include/c++/14.1.1/bits/invoke.h:60
#36 std::__invoke<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&>(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&) (
    __fn=...) at /usr/include/c++/14.1.1/bits/invoke.h:97
#37 std::invoke<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&>(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&) (
    __fn=...) at /usr/include/c++/14.1.1/functional:121
#38 QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1}::operator()(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}) const (__closure=<synthetic pointer>, function=...)
    at /usr/include/qt6/QtConcurrent/qtconcurrentstoredfunctioncall.h:116
#39 std::__invoke_impl<Fooyin::CoverProvider::Private::CoverLoaderResult, QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>(std::__invoke_other, QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&&) (__f=<synthetic pointer>...) at /usr/include/c++/14.1.1/bits/invoke.h:61
#40 std::__invoke<QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>(QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}&&) (__fn=<synthetic pointer>...) at /usr/include/c++/14.1.1/bits/invoke.h:97
#41 std::__apply_impl<QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, std::tuple<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>, 0ul>(QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, std::tuple<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>&&, std::integer_sequence<unsigned long, 0ul>) (__f=<synthetic pointer>..., __t=...) at /usr/include/c++/14.1.1/tuple:2922
#42 std::apply<QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, std::tuple<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}> >(QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor()::{lambda(Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1})#1} const&, std::tuple<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>&&) (__f=<synthetic pointer>..., __t=...) at /usr/include/c++/14.1.1/tuple:2938
#43 QtConcurrent::StoredFunctionCall<Fooyin::CoverProvider::Private::fetchCover(QString const&, Fooyin::Track const&, Fooyin::Track::Cover, bool)::{lambda()#1}>::runFunctor() (this=0x5555562f3500) at /usr/include/qt6/QtConcurrent/qtconcurrentstoredfunctioncall.h:122
#44 QtConcurrent::RunFunctionTaskBase<Fooyin::CoverProvider::Private::CoverLoaderResult>::run (this=0x5555562f3500) at /usr/include/qt6/QtConcurrent/qtconcurrentrunbase.h:83
```

Perhaps a text encoding issue? I have a lot of Japanese files, including cover art files with Japanese characters. Note that this playlist is old and so the track had no issues in older versions.

**Comment by ludouzi** [comment]
If it was fine previously, then I suspect this is caused by a race condition from switching to a shared mutex. https://github.com/fooyin/fooyin/commit/c300f8ba43f5b1576d035f6c497301a3a74acf22 restores some of the original behaviour.

**Comment by kode54** [comment]
Not sure if this is related to an issue I had with playlists after restarting the player recently, not having updated yet. It restarted, and the "Playing" column was suddenly taking up the entire width of the player window, with all the other columns shifted off the screen.

**Comment by ludouzi** [comment]
That may be an issue with the playlist header state which is saved to the layout file. Someone reported something similar earlier https://github.com/fooyin/fooyin/issues/159, though the header wasn't even shown.

I've found this can also happen with other widgets which use AutoHeaderView like the library filters. I haven't been able to  consistently reproduce it thus far, but I'll have another go.

**Comment by ripdog** [comment]
Oh sorry, I completely forgot to comment on this! I can confirm that my bug is fixed, so I'll go ahead and close this.

Many thanks as always!
