### ISSUE TITLE
22050Hz Mono MP3 file crashes PipeWire output on completion or transition to a stereo track

### ISSUE THREAD

**Issue by kode54** [fooyin/fooyin#185]
**Describe the bug**
I am slogging through the OverClocked ReMixes back catalogue again, and hit OCR00209, or Legend of Zelda "The Music of My Groin", which is a rare 22050Hz Mono 128kbps MP3 file. Upon playing to completion and switching to the next track, the PipeWire output crashes the player.

**To Reproduce**
1. Add a 22050Hz mono (or possibly just mono) track to the playlist, followed by a stereo file, possibly of a different sample rate.
2. Configure Engine to PipeWire output.
3. Play the mono file.
4. Allow it to play to completion, and start playing a stereo file.

**Expected behaviour**
The files should play back seamlessly.

**System:**
 - OS: Arch Linux
 - fooyin version: fooyin-git r2523.cdcb6459-1

**Additional context**
I probably haven't updated the player in a bit, so I'll try updating it soonish. I'll grab a backtrace, too:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007031fb6a8eb3 in __pthread_kill_internal (threadid=<optimized out>, signo=6)
    at pthread_kill.c:78
#2  0x00007031fb650a30 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007031fb6384c3 in __GI_abort () at abort.c:79
#4  0x00007031fb639354 in __libc_message_impl (fmt=fmt@entry=0x7031fb7c22ea "%s\n")
    at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007031fb6b3085 in malloc_printerr (
    str=str@entry=0x7031fb7c5488 "double free or corruption (!prev)") at malloc.c:5772
#6  0x00007031fb6b524c in _int_free_merge_chunk (av=av@entry=0x7031b4000030, 
    p=0x7031b4020760, size=30256) at malloc.c:4679
#7  0x00007031fb6b554a in _int_free (av=0x7031b4000030, p=p@entry=0x7031b4020760, 
    have_lock=<optimized out>, have_lock@entry=0) at malloc.c:4646
#8  0x00007031fb6b7dae in __GI___libc_free (mem=0x7031b4020770) at malloc.c:3398
#9  0x00007031dd9f18a4 in clear_buffers (this=0x7031cc0a3088)
    at ../pipewire/spa/plugins/audioconvert/audioadapter.c:492
#10 configure_format (this=this@entry=0x7031cc0a3088, flags=flags@entry=0, 
    format=<optimized out>, format@entry=0x0)
    at ../pipewire/spa/plugins/audioconvert/audioadapter.c:540
#11 0x00007031dd9f38fc in impl_node_send_command (object=0x7031cc0a3088, 
    command=0x7031dedff050) at ../pipewire/spa/plugins/audioconvert/audioadapter.c:993
#12 0x00007031e413456f in suspend_node (this=this@entry=0x7031cc095580)
    at ../pipewire/src/pipewire/impl-node.c:494
#13 0x00007031e4133904 in pw_impl_node_set_state (node=node@entry=0x7031cc095580, 
    state=state@entry=PW_NODE_STATE_SUSPENDED) at ../pipewire/src/pipewire/impl-node.c:2700
#14 0x00007031dda90e05 in client_node_removed (_data=0x7031cc04eee8)
    at ../pipewire/src/modules/module-client-node/remote-node.c:1127
#15 0x00007031e4144dc8 in pw_proxy_destroy (proxy=0x7031cc04ee70)
    at ../pipewire/src/pipewire/proxy.c:230
#16 0x00007031e414ab8c in stream_disconnect (impl=0x7031cc03fa80)
    at ../pipewire/src/pipewire/stream.c:1616
#17 0x00007031e41fa179 in Fooyin::Pipewire::PipewireStream::PwStreamDeleter::operator() (
    this=<optimized out>, stream=0x7031cc03fa80)
    at /usr/src/debug/fooyin-git/fooyin-git/src/plugins/pipewire/pipewirestream.h:61
#18 Fooyin::Pipewire::PipewireStream::PwStreamDeleter::operator() (this=<optimized out>, 
    stream=0x7031cc03fa80)
    at /usr/src/debug/fooyin-git/fooyin-git/src/plugins/pipewire/pipewirestream.h:58
#19 std::unique_ptr<pw_stream, Fooyin::Pipewire::PipewireStream::PwStreamDeleter>::~unique_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:398
#20 Fooyin::Pipewire::PipewireStream::~PipewireStream (this=<optimized out>, 
    this=<optimized out>)
    at /usr/src/debug/fooyin-git/fooyin-git/src/plugins/pipewire/pipewirestream.cpp:59
#21 std::default_delete<Fooyin::Pipewire::PipewireStream>::operator() (
    this=<optimized out>, __ptr=0x7031cc01c840)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:93
#22 std::default_delete<Fooyin::Pipewire::PipewireStream>::operator() (
    this=<optimized out>, __ptr=0x7031cc01c840)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:87
#23 std::__uniq_ptr_impl<Fooyin::Pipewire::PipewireStream, std::default_delete<Fooyin::Pipewire::PipewireStream> >::reset (this=0x7031cc0014c8, __p=0x0)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:205
#24 std::unique_ptr<Fooyin::Pipewire::PipewireStream, std::default_delete<Fooyin::Pipewire::PipewireStream> >::reset (this=0x7031cc0014c8, __p=0x0)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:503
#25 Fooyin::Pipewire::PipeWireOutput::Private::uninit (this=0x7031cc001470)
    at /usr/src/debug/fooyin-git/fooyin-git/src/plugins/pipewire/pipewireoutput.cpp:151
#26 0x00007031e41faac1 in Fooyin::Pipewire::PipeWireOutput::uninit (this=<optimized out>)
    at /usr/src/debug/fooyin-git/fooyin-git/src/plugins/pipewire/pipewireoutput.cpp:337
#27 0x00007031fd555f8e in Fooyin::AudioRenderer::init (this=0x6116c56cec10, format=...)
    at /usr/include/c++/14.1.1/bits/unique_ptr.h:193
#28 0x00007031fd55c9bb in Fooyin::AudioPlaybackEngine::Private::updateFormat (
    this=<optimized out>, nextFormat=...)
    at /usr/src/debug/fooyin-git/fooyin-git/src/core/engine/audioplaybackengine.cpp:276
#29 Fooyin::AudioPlaybackEngine::changeTrack (this=<optimized out>, track=...)
    at /usr/src/debug/fooyin-git/fooyin-git/src/core/engine/audioplaybackengine.cpp:429
#30 0x00007031fbd8c00f in QObject::event (this=0x6116c56cebc0, e=0x7031cc073a80)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:1452
#31 0x00007031fccfc51c in QApplicationPrivate::notify_helper (this=<optimized out>, 
    receiver=0x6116c56cebc0, e=0x7031cc073a80)
    at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3287
#32 0x00007031fbd44d28 in QCoreApplication::notifyInternal2 (receiver=0x6116c56cebc0, 
    event=event@entry=0x7031cc073a80)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1142
#33 0x00007031fbd450eb in QCoreApplication::sendEvent (receiver=<optimized out>, 
    event=0x7031cc073a80)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1583
#34 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, 
    data=0x6116c56cdc30)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1940
#35 0x00007031fbfa49ec in QCoreApplication::sendPostedEvents (receiver=0x0, event_type=0)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1797
#36 postEventSourceDispatch (s=0x7031cc000f20)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:244
#37 0x00007031f890eab9 in g_main_dispatch (context=0x7031cc000c60)
    at ../glib/glib/gmain.c:3344
#38 0x00007031f89709e7 in g_main_context_dispatch_unlocked (context=0x7031cc000c60)
    at ../glib/glib/gmain.c:4152
#39 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7031cc000c60, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4217
#40 0x00007031f890dfc5 in g_main_context_iteration (context=0x7031cc000c60, may_block=1)
    at ../glib/glib/gmain.c:4282
#41 0x00007031fbfa2cbd in QEventDispatcherGlib::processEvents (this=0x7031cc000b70, 
    flags=...)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:394
#42 0x00007031fbd4f01e in QEventLoop::processEvents (this=0x7031dedff830, flags=...)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:100
#43 QEventLoop::exec (this=0x7031dedff830, flags=...)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:182
#44 0x00007031fbe3a560 in QThread::exec (this=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread.cpp:586
#45 QThread::run (this=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread.cpp:707
#46 0x00007031fbec9747 in operator() (__closure=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:326
#47 (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::<lambda()> >
    (t=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:262
#48 QThreadPrivate::start (arg=0x6116c56c4fb8)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:285
#49 0x00007031fb6a6ded in start_thread (arg=<optimized out>) at pthread_create.c:447
#50 0x00007031fb72a0dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

Oh, lovely, looks like memory corruption.

Edit: Ah, looks like it's another case of 22050Hz file.

**Comment by ludouzi** [comment]
Thanks to ASAN, I was able to easily find the cause. Should be fixed with https://github.com/fooyin/fooyin/commit/1438de8f5d8d8d13441f8b0ef16dec3638141d44.

**Comment by kode54** [comment]
Awesome, I'll try it out tonight.

**Comment by kode54** [comment]
Oops, I forgot to verify and close this. Definitely fixed, closing.
